const fs = require('fs')
const path = require('path')

const PLUGINS_DIR = path.join(__dirname, '..', 'src', 'plugins')
const OUTPUT_FILE = path.join(PLUGINS_DIR, '_generated.ts')
const REWRITES_FILE = path.join(PLUGINS_DIR, '_rewrites.ts')
const SCHEMA_BASE = path.join(__dirname, '..', 'prisma', 'schema.base.prisma')
const SCHEMA_OUTPUT = path.join(__dirname, '..', 'prisma', 'schema.prisma')

function scanPlugins() {
  if (!fs.existsSync(PLUGINS_DIR)) {
    fs.mkdirSync(PLUGINS_DIR, { recursive: true })
  }

  const entries = fs.readdirSync(PLUGINS_DIR, { withFileTypes: true })
  const folders = entries
    .filter(e => e.isDirectory() && !e.name.startsWith('_'))
    .map(e => e.name)

  const plugins = []
  const slugs = new Map()

  for (const folder of folders) {
    const pluginFile = path.join(PLUGINS_DIR, folder, 'plugin.ts')
    if (!fs.existsSync(pluginFile)) {
      console.warn(`[scan-plugins] Warning: ${folder}/ has no plugin.ts, skipping`)
      continue
    }

    const content = fs.readFileSync(pluginFile, 'utf-8')
    const getName = (key) => {
      const match = content.match(new RegExp(`${key}:\\s*['"\`]([^'"\`]+)['"\`]`))
      return match ? match[1] : ''
    }
    const getBool = (key) => {
      const match = content.match(new RegExp(`${key}:\\s*(true|false)`))
      return match ? match[1] === 'true' : false
    }

    const name = getName('name') || folder
    const slug = getName('slug') || folder
    const version = getName('version') || '0.0.0'
    const author = getName('author') || ''
    const authorDomain = getName('authorDomain') || ''
    const repository = getName('repository') || ''
    const description = getName('description') || ''
    const defaultEnabled = getBool('defaultEnabled')

    if (slugs.has(slug)) {
      console.error(`ERROR: slug '${slug}' conflict!`)
      console.error(`  - src/plugins/${slugs.get(slug)}/plugin.ts`)
      console.error(`  - src/plugins/${folder}/plugin.ts`)
      console.error(`Change one of the slugs to resolve.`)
      process.exit(1)
    }
    slugs.set(slug, folder)

    const hasRoutes = fs.existsSync(path.join(PLUGINS_DIR, folder, 'routes'))
    const hasApi = fs.existsSync(path.join(PLUGINS_DIR, folder, 'api'))
    const hasAdmin = fs.existsSync(path.join(PLUGINS_DIR, folder, 'admin'))
    const hasWidgets = fs.existsSync(path.join(PLUGINS_DIR, folder, 'widgets'))
    const hasMenus = fs.existsSync(path.join(PLUGINS_DIR, folder, 'menus'))
    const hasSchema = fs.existsSync(path.join(PLUGINS_DIR, folder, 'schema.prisma'))

    plugins.push({
      folder, name, slug, version, author, authorDomain, repository,
      description, defaultEnabled, hasRoutes, hasApi, hasAdmin,
      hasWidgets, hasMenus, hasSchema,
    })
  }

  console.log(`[scan-plugins] Found ${plugins.length} plugin(s): ${plugins.map(p => p.folder).join(', ')}`)

  generateManifest(plugins)
  generateRewrites(plugins)
  mergeSchemas(plugins)
}

function generateManifest(plugins) {
  const entries = plugins.map(p => {
    return `  '${p.folder}': {
    name: '${p.name}',
    slug: '${p.slug}',
    version: '${p.version}',
    author: '${p.author}',
    authorDomain: '${p.authorDomain}',
    repository: '${p.repository}',
    description: '${p.description}',
    defaultEnabled: ${p.defaultEnabled},
    hasRoutes: ${p.hasRoutes},
    hasApi: ${p.hasApi},
    hasAdmin: ${p.hasAdmin},
    hasWidgets: ${p.hasWidgets},
    hasMenus: ${p.hasMenus},
    hasSchema: ${p.hasSchema},
  }`
  })

  const output = `// AUTO-GENERATED by scripts/scan-plugins.js — do not edit manually

export interface PluginMeta {
  name: string
  slug: string
  version: string
  author: string
  authorDomain: string
  repository: string
  description: string
  defaultEnabled: boolean
  hasRoutes: boolean
  hasApi: boolean
  hasAdmin: boolean
  hasWidgets: boolean
  hasMenus: boolean
  hasSchema: boolean
}

export const pluginManifest: Record<string, PluginMeta> = {
${entries.join(',\n')}
}

export type PluginFolder = keyof typeof pluginManifest
`

  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8')
  console.log(`[scan-plugins] Generated ${OUTPUT_FILE}`)
}

function generateRewrites(plugins) {
  const rewrites = []

  for (const p of plugins) {
    if (p.hasRoutes) {
      rewrites.push(`  { source: '/${p.slug}/:path*', destination: '/plugins/${p.folder}/routes/:path*' }`)
      rewrites.push(`  { source: '/${p.slug}', destination: '/plugins/${p.folder}/routes' }`)
    }
    if (p.hasApi) {
      rewrites.push(`  { source: '/api/${p.slug}/:path*', destination: '/plugins/${p.folder}/api/:path*' }`)
      rewrites.push(`  { source: '/api/${p.slug}', destination: '/plugins/${p.folder}/api' }`)
    }
    if (p.hasAdmin) {
      const adminPagePath = path.join(PLUGINS_DIR, p.folder, 'admin', 'page.tsx')
      if (fs.existsSync(adminPagePath)) {
        rewrites.push(`  { source: '/admin/${p.slug}/:path*', destination: '/plugins/${p.folder}/admin/:path*' }`)
        rewrites.push(`  { source: '/admin/${p.slug}', destination: '/plugins/${p.folder}/admin' }`)
      }
      const adminApiPath = path.join(PLUGINS_DIR, p.folder, 'admin', 'api')
      if (fs.existsSync(adminApiPath)) {
        rewrites.push(`  { source: '/api/admin/${p.slug}/:path*', destination: '/plugins/${p.folder}/admin/api/:path*' }`)
        rewrites.push(`  { source: '/api/admin/${p.slug}', destination: '/plugins/${p.folder}/admin/api' }`)
      }
    }
  }

  const output = `// AUTO-GENERATED by scripts/scan-plugins.js — do not edit manually
import type { Rewrite } from 'next/dist/lib/load-custom-routes'

export const pluginRewrites: Rewrite[] = [
${rewrites.join(',\n')}
]
`

  fs.writeFileSync(REWRITES_FILE, output, 'utf-8')
  console.log(`[scan-plugins] Generated ${REWRITES_FILE}`)
}

function mergeSchemas(plugins) {
  let baseSchema = ''
  if (fs.existsSync(SCHEMA_BASE)) {
    baseSchema = fs.readFileSync(SCHEMA_BASE, 'utf-8')
  } else {
    const currentSchema = path.join(__dirname, '..', 'prisma', 'schema.prisma')
    if (fs.existsSync(currentSchema)) {
      baseSchema = fs.readFileSync(currentSchema, 'utf-8')
      fs.writeFileSync(SCHEMA_BASE, baseSchema, 'utf-8')
      console.log(`[scan-plugins] Created ${SCHEMA_BASE} from existing schema.prisma`)
    }
  }

  const pluginSchemas = []
  for (const p of plugins) {
    if (p.hasSchema) {
      const schemaPath = path.join(PLUGINS_DIR, p.folder, 'schema.prisma')
      const content = fs.readFileSync(schemaPath, 'utf-8')
      pluginSchemas.push(`\n// ======= Plugin: ${p.folder} =======\n${content}`)
    }
  }

  const merged = `// AUTO-GENERATED by scripts/scan-plugins.js — do not edit manually
// Edit prisma/schema.base.prisma for core models
// Edit src/plugins/*/schema.prisma for plugin models

${baseSchema}
${pluginSchemas.join('\n')}
`

  fs.writeFileSync(SCHEMA_OUTPUT, merged, 'utf-8')
  console.log(`[scan-plugins] Merged ${pluginSchemas.length} plugin schema(s) into ${SCHEMA_OUTPUT}`)
}

scanPlugins()
