// AUTO-GENERATED by scripts/scan-plugins.js — do not edit manually
import type { Rewrite } from 'next/dist/lib/load-custom-routes'

export const pluginRewrites: Rewrite[] = [
  { source: '/sample/:path*', destination: '/plugins/sample/routes/:path*' },
  { source: '/sample', destination: '/plugins/sample/routes' },
  { source: '/api/sample/:path*', destination: '/plugins/sample/api/:path*' },
  { source: '/api/sample', destination: '/plugins/sample/api' }
]
