// AUTO-GENERATED by scripts/scan-layouts.js — do not edit manually
import dynamic from 'next/dynamic'
import type { ComponentType } from 'react'

export const layoutManifest = {
  "default": {
    "name": "default",
    "files": {
      "Header": true,
      "HomePage": true,
      "Footer": true
    }
  }
} as const

export type LayoutFolder = keyof typeof layoutManifest
export type LayoutComponent = 'Header' | 'HomePage' | 'Footer'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const componentMap: Record<string, ComponentType<any>> = {
  'default/Header': dynamic(() => import('@/layouts/default/Header'), { ssr: false }),
  'default/HomePage': dynamic(() => import('@/layouts/default/HomePage'), { ssr: false }),
  'default/Footer': dynamic(() => import('@/layouts/default/Footer'), { ssr: false })
}
